;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Interact",DevComment="Check for interaction")
+GameplayTagList=(Tag="Movement",DevComment="Gameplay Tag that check any kind of movement")
+GameplayTagList=(Tag="Movement.Crouch",DevComment="")
+GameplayTagList=(Tag="Movement.Fall",DevComment="Check for fall")
+GameplayTagList=(Tag="Movement.Idle",DevComment="Check Idle")
+GameplayTagList=(Tag="Movement.Jump",DevComment="Check for jump")
+GameplayTagList=(Tag="Movement.Peaking",DevComment="Check for when character peak")
+GameplayTagList=(Tag="Movement.Peaking.Left",DevComment="Check character peaking left")
+GameplayTagList=(Tag="Movement.Peaking.Right",DevComment="Check character peaking right")
+GameplayTagList=(Tag="Movement.Running",DevComment="Check if running")
+GameplayTagList=(Tag="Movement.Walking",DevComment="Check if walking")

